set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle Plugins
Plugin 'airblade/vim-rooter'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'sickill/vim-pasta'
Plugin 'Lokaltog/vim-powerline'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-commentary'
Plugin 'mileszs/ack.vim'
Plugin 'Raimondi/delimitMate'
Plugin 'ervandew/supertab'
Plugin 'plasticboy/vim-markdown'
Plugin 'airblade/vim-gitgutter'
Plugin 'helino/vim-json'
Plugin 'w0ng/vim-hybrid'
Plugin 'flazz/vim-colorschemes'
Plugin 'pangloss/vim-javascript'
Plugin 'puppetlabs/puppet-syntax-vim'
Plugin 'mxw/vim-jsx'
Plugin 'fatih/vim-go'
Plugin 'groenewege/vim-less'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'sophacles/vim-processing'
Plugin 'tpope/vim-obsession'
Plugin 'rking/ag.vim'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'burnettk/vim-angular'
Plugin 'dkprice/vim-easygrep'

" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required

map <C-n> :NERDTreeToggle<CR>

let g:ctrlp_custom_ignore = {
      \ 'dir': '\v[\/](haproxy-1.4.20|node_modules|.git|yui-compressor)$',
      \ }

" enable syntastic
let g:syntastic_enable_signs=1
let g:syntastic_auto_loc_list=1
let g:syntastic_disabled_filetypes = ['sass', 'html']
map <F5> :SyntasticToggleMode<CR>:redraw!<CR>

" enable syntastic for c
let g:syntastic_c_check_header = 1
let g:syntastic_c_auto_refresh_includes = 1
let b:syntastic_c_cflags = ' -std=c99'

au BufRead,BufNewFile *.json set filetype=json
au BufRead,BufNewFile .jshintrc set filetype=javascript

" syntax highlighting
syntax on
colorscheme monokai

set guifont=Inconsolata-dz\ for\ Powerline:h14

" lots of colors!
set t_Co=256

set noswapfile

" indenting
filetype indent on
set autoindent

set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab

" tabs should be two spaces always
set ts=2
set smarttab
"set expandtab
set noexpandtab
set shiftwidth=2

" default sizes
set colorcolumn=80

" fold method
set foldmethod=syntax
set foldnestmax=4      "deepest fold is 10 levels"
set nofoldenable
set nowrap

" show matching braces, brackets, etc
set showmatch

set smartcase

" highlight search
set hlsearch
" search character by character
set incsearch

" Better file completion
set wildmenu
set wildmode=list:longest

" turn on line numbering
set nu

" turn on mouse
set mouse=a

" fixes backspace
set backspace=indent,eol,start

fun! <SID>StripTrailingWhitespaces()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfun
autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

au BufRead,BufNewFile *.md set filetype=markdown
autocmd BufWritePre *.py :%s/\s\+$//e
